### ISSUE TITLE
Clients sending bad messages could hang

### ISSUE THREAD

**Issue by pkivolowitz** [pkivolowitz/pas#16]
Suppose the client issues a who on device 99. The server will ignore it. The client may hang trying to get a response. The server should send back ErrorMessages.

**Comment by pkivolowitz** [comment]
This has been remedied. On unknown message, pas will send back UNKNOWN_MESSAGE.
Our two existing clients required no modification!

**Comment by LOZORD** [comment]
That sounds smart to me. A common practice with protos is to have defined "unknown" values with enums and any other related cases. This is a safe way to handle weird (though not uncommon) cases. Because everything is (and _should_ be) optional with proto3, having defined "unknown" default values is the right way to do things.
